language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py migrate
  - python manage.py test restaurant
after-success:
  - echo $SSH_KEY > /tmp/key
  - ssh -o "StrictHostKeyChecking no" -i "/tmp/key" $DEPLOY_ACCOUNT@$DOMAIN_NAME $DEPLOY_COMMAND
